version: "3"
services:
  app:
    build: ./sample
    expose:
      - 3000
      
  waiter1:
    image: waisbrot/wait
    environment:
      - TARGETS=app:3000
      - TIMEOUT=300
    depends_on:
      - app

  waiter2:
    image: lbalmaceda/url-wait
    environment:
      - URL=app:3000
      - TIMEOUT=300
    depends_on:
      - app

  tester:
    image: codeception/codeceptjs
    depends_on: 
      - waiter1
      - waiter2
    environment:
      - WEBAPP_URL=app:3000